### ISSUE TITLE
Make this a `GitHub Pages` so we can view just by going to tooltip.matthias-schuetz.github.io

### ISSUE THREAD

**Issue by DaCuteRaccoon** [matthias-schuetz/Tooltip#10]
[site]: https://matthias-scheutz.github.io/

**Comment by matthias-schuetz** [comment]
Thanks for the info, I've finally found the time to update my Git repositories.
The tooltip page is now updated and can be viewed on https://matthias-schuetz.github.io/tooltip.js/.
