### ISSUE TITLE
refresh tooltips when part of dom is reloaded

### ISSUE THREAD

**Issue by kmanley** [matthias-schuetz/Tooltip#2]
I sometimes use libs like intercoolerjs to dynamically replace parts of my dom. When I do this, it sometimes makes the tooltip lib misbehave. It would be great to have a refresh() function in the tooltip lib to handle this case.

**Comment by matthias-schuetz** [comment]
OK, no problem. I've added the `tooltip.refresh()` method to the library. So if you get the latest version, simply call refresh() after updating/replacing the DOM and the tooltips will be rebuilt.

**Comment by kmanley** [comment]
That's great -- thanks a lot!
