### ISSUE TITLE
Firefox display issue when adding tooltip to SVG polygon (tooltip appears below element)

### ISSUE THREAD

**Issue by zrobe** [matthias-schuetz/Tooltip#3]
Hello, 

Thank you for the work you put in this awesome project.
I'm new here and didn't know where to comment this issue so please be mindful. 

I'm using this on a website containing a SVG and it works wonderful on Chrome but i discovered that on Firefox 49.0.1, the tooltip is displayed below/under the SVG.

An easy fix to this is to add a "z-index" to the tooltip.css
I added z-index: 999 if it is of any importance.

Thank you again, 
Have a great day.

**Comment by matthias-schuetz** [comment]
Thanks! I've added the `z-index: 999;` to the CSS. But the Z-layering of a website is another topic, so 999 depends on the page layout and other components of a project.
